[[proxy]]
    from = "*"
    to = "https://xkcd.com/"
    status = 200

[[redirects]]
  from = "/api/*"
  to = "https://xkcd.com/:splat"
  status = 200
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
